maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 20)
basic.pause(1000)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 20)
basic.pause(1000)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 20)
basic.pause(1000)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 20)
basic.pause(1000)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 20)
basic.pause(1000)
maqueen.motorStop(maqueen.Motors.All)
basic.forever(function () {
	
})
